vscode:
  extensions:
    - dracula-theme.theme-dracula@2.18.1:XgpbxhhUSPGI4YfNBYpr1A==
    - rocketseat.RocketseatReactJS@2.2.0:CMZI2JF+9mcg15CoJkRPOQ==
    - rocketseat.RocketseatReactNative@2.2.0:R1GKe6htx17bP/HX+6BUFQ==
    - PKief.material-icon-theme@3.9.1:g1O+jL+iaYZp5mMmzpPEug==